packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  sharp: true
  unrs-resolver: true

# Izinkan package berikut menjalankan post-install scripts (pnpm v10+ strict mode).
onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - sharp
  - unrs-resolver
